name: CI

on:
  push:
    branches:
      - '**'
      - '!integrated/**'
      - '!stl-preview-head/**'
      - '!stl-preview-base/**'
      - '!generated'
      - '!codegen/**'
      - 'codegen/stl/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 30
    name: test
    runs-on: ${{ github.repository == 'stainless-sdks/cloudflare-python' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          version: '0.10.2'

      - name: Bootstrap
        run: ./scripts/bootstrap
        env:
          UV_PYTHON: ">=3.14.0"

      - name: Run tests
        continue-on-error: true
        run: ./scripts/test
        env:
          UV_PYTHON: ">=3.14.0"

  examples:
    timeout-minutes: 10
    name: examples
    continue-on-error: true
    runs-on: ${{ github.repository == 'stainless-sdks/cloudflare-python' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.repository == 'cloudflare/cloudflare-python' && (github.event_name == 'push' || github.event.pull_request.head.repo.fork) && (github.event_name != 'push' || github.event.head_commit.message != 'codegen metadata')

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          version: '0.10.2'
      - name: Install dependencies
        run: uv sync --all-extras

      - env:
          CLOUDFLARE_ACCOUNT_ID: f037e56e89293a057740de681ac9abbe
          CLOUDFLARE_EMAIL: terraform-acceptance-test@cfapi.net
          CLOUDFLARE_ZONE_ID: 0da42c8d2132a9ddaf714f9e7c920711
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        run: |
            uv run python ./examples/dns/record.py
